// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RapidRelief.Api.Features.Relief.Data;

#nullable disable

namespace RapidRelief.Api.Features.Relief.Data.Migrations
{
    [DbContext(typeof(ReliefDbContext))]
    partial class ReliefDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RapidRelief.Api.Features.Relief.Domain.ReliefDispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarrierOrPartner")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DispatchedByUserId")
                        .HasColumnType("uuid");

                    b.Property<double>("DispatchedQuantity")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ReliefRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ReliefRequestId");

                    b.HasIndex("ResourceId");

                    b.ToTable("relief_dispatches", (string)null);
                });

            modelBuilder.Entity("RapidRelief.Api.Features.Relief.Domain.ReliefRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityRequested")
                        .HasColumnType("integer");

                    b.Property<int>("RecipientCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReliefType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UrgencyLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.HasIndex("Status");

                    b.ToTable("relief_requests", (string)null);
                });

            modelBuilder.Entity("RapidRelief.Api.Features.Relief.Domain.ReliefResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AllocatedQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<double>("TotalQuantity")
                        .HasColumnType("double precision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WarehouseLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("relief_resources", (string)null);
                });

            modelBuilder.Entity("RapidRelief.Api.Features.Relief.Domain.ReliefDispatch", b =>
                {
                    b.HasOne("RapidRelief.Api.Features.Relief.Domain.ReliefRequest", "ReliefRequest")
                        .WithMany("Dispatches")
                        .HasForeignKey("ReliefRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RapidRelief.Api.Features.Relief.Domain.ReliefResource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReliefRequest");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("RapidRelief.Api.Features.Relief.Domain.ReliefRequest", b =>
                {
                    b.Navigation("Dispatches");
                });
#pragma warning restore 612, 618
        }
    }
}
