// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RapidRelief.Api.Features.Ai.Data;

#nullable disable

namespace RapidRelief.Api.Features.Ai.Data.Migrations
{
    [DbContext(typeof(AiDbContext))]
    [Migration("20260901195555_DuplicateScanIndex")]
    partial class DuplicateScanIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RapidRelief.Api.Features.Ai.Domain.AiAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedSeverity")
                        .HasColumnType("integer");

                    b.Property<string>("FinishReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("PossibleDuplicateOfId")
                        .HasColumnType("uuid");

                    b.Property<int>("PredictedType")
                        .HasColumnType("integer");

                    b.Property<double>("PriorityScore")
                        .HasColumnType("double precision");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("SnapshotIsSos")
                        .HasColumnType("boolean");

                    b.Property<double>("SnapshotLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("SnapshotLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("SnapshotReportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SnapshotType")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId")
                        .IsUnique();

                    b.HasIndex("SnapshotType", "SnapshotReportedAtUtc");

                    b.ToTable("ai_assessments", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
